# Generated by Django 5.0.4 on 2024-05-04 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
