# Generated by Django 5.0.4 on 2024-04-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeartDiseaseorAttack', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('HighBP', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('HighChol', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('CholCheck', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('IMC', models.IntegerField()),
                ('Smoker', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('Stroke', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('Diabetes', models.IntegerField(choices=[(0, 'No'), (1, 'Prediabetes'), (2, 'Tipo 1'), (3, 'Tipo 2')])),
                ('PhysActivity', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('Fruits', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('Veggies', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('HvyAlcoholConsump', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('AnyHealthcare', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('NoDocbcCost', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('GenHlth', models.IntegerField(choices=[(1, 'Excelente'), (2, 'Muy buena'), (3, 'Buena'), (4, 'Regular'), (5, 'Mala')])),
                ('Menthlth', models.IntegerField()),
                ('PhysHlth', models.IntegerField()),
                ('DiffWalk', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('Sex', models.IntegerField(choices=[(0, 'Mujer'), (1, 'Hombre')])),
                ('Age', models.IntegerField(choices=[(1, '18-24 años'), (2, '25-29 años'), (3, '30-34 años'), (4, '35-39 años'), (5, '40-44 años'), (6, '45-49 años'), (7, '50-54 años'), (8, '55-59 años'), (9, '60-64 años'), (10, '65-69 años'), (11, '70-74 años'), (12, '75-79 años'), (13, '80 años o más')])),
                ('Education', models.IntegerField(choices=[(0, 'Nunca asistió o solo asistió al jardín de infancia'), (1, '1er grado'), (2, '2do grado'), (3, '3er grado'), (4, '4to grado'), (5, '5to grado'), (6, '4 años de universidad o más')])),
                ('Income', models.IntegerField(choices=[(1, 'Menos de 10,000 $'), (2, '10,000 - 14,999 $'), (3, '15,000 - 24,999 $'), (4, '25,000 - 34,999 $'), (5, '35,000 - 49,999 $'), (6, 'Más de 50,000 $')])),
            ],
        ),
    ]
