# Generated by Django 5.0.4 on 2024-09-08 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiax', '0002_analytic_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='anyHealthcare',
            new_name='exerciseInducedAngina',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='cholCheck',
            new_name='fastingBloodSugar',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='diffWalk',
            new_name='heartDisease',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='imc',
            new_name='maximumHeartRateAchieved',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='diabetes',
            new_name='numberOfMajorVessels',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='menthlth',
            new_name='restingBloodPressure',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='physHlth',
            new_name='serumCholestoral',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='education',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='fruits',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='genHlth',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='heartDiseaseorAttack',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='highBP',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='highChol',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='hvyAlcoholConsump',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='income',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='noDocbcCost',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='physActivity',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='smoker',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='stroke',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='veggies',
        ),
        migrations.AddField(
            model_name='analytic',
            name='chestPainType',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analytic',
            name='oldpeak',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analytic',
            name='restingElectrocardiographicResults',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analytic',
            name='slopeOfThePeakExercise',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analytic',
            name='thal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analytic',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
